<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="style/styleHome.css">
    <meta charset="UTF-8">
</head>
<body>
<nav>
    <a href="/home"><img src="images/logo2.jpg"></a>
    <div class="nav-links">
        <ul>
            <li><a href="/home">HOME</a></li>
            <li><a href="/allPosts">WEATHER</a></li>
            <li><a href="/profile">PROFILE</a></li>
        </ul>
    </div>
</nav>

</body>
</html>